# createdb
# Autogenerated from man page /usr/share/man/man1/createdb.1.gz
complete -c createdb -s D --description 'Specifies the default tablespace for the database.'
complete -c createdb -o 'e
.br
--echo' --description 'Echo the commands that createdb generates and sends to the server.'
complete -c createdb -s E --description 'Specifies the character encoding scheme to be used in this database.'
complete -c createdb -s l --description 'Specifies the locale to be used in this database.'
complete -c createdb -l lc-collate --description 'Specifies the LC_COLLATE setting to be used in this database.'
complete -c createdb -l lc-ctype --description 'Specifies the LC_CTYPE setting to be used in this database.'
complete -c createdb -s O --description 'Specifies the database user who will own the new database.'
complete -c createdb -s T --description 'Specifies the template database from which to build this database.'
complete -c createdb -o 'V
.br
--version' --description 'Print the createdb version and exit.'
complete -c createdb -o '?
.br
--help' --description 'Show help about createdb command line arguments, and exit.'
complete -c createdb -s h --description 'Specifies the host name of the machine on which the server is running.'
complete -c createdb -s p --description 'Specifies the TCP port or the local Unix domain socket file extension on whic…'
complete -c createdb -s U --description 'User name to connect as.'
complete -c createdb -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c createdb -o 'W
.br
--password' --description 'Force createdb to prompt for a password before connecting to a database.'
complete -c createdb -l maintenance-db --description 'Specifies the name of the database to connect to when creating the new databa…'
complete -c createdb -l tablespace --description '.'
complete -c createdb -s e --description '.'
complete -c createdb -l echo --description '.'
complete -c createdb -l encoding --description '.'
complete -c createdb -l locale --description '.'
complete -c createdb -l owner --description '.'
complete -c createdb -l template --description '.'
complete -c createdb -s V --description '.'
complete -c createdb -l version --description '.'
complete -c createdb -s '?' --description '.'
complete -c createdb -l help --description '.'
complete -c createdb -l host --description '.'
complete -c createdb -l port --description '.'
complete -c createdb -l username --description '.'
complete -c createdb -s w --description '.'
complete -c createdb -l no-password --description '.'
complete -c createdb -s W --description '.'
complete -c createdb -l password --description '.'

