# dropdb
# Autogenerated from man page /usr/share/man/man1/dropdb.1.gz
complete -c dropdb -o 'e
.br
--echo' --description 'Echo the commands that dropdb generates and sends to the server.'
complete -c dropdb -o 'i
.br
--interactive' --description 'Issues a verification prompt before doing anything destructive.'
complete -c dropdb -o 'V
.br
--version' --description 'Print the dropdb version and exit.'
complete -c dropdb -l if-exists --description 'Do not throw an error if the database does not exist.'
complete -c dropdb -o '?
.br
--help' --description 'Show help about dropdb command line arguments, and exit.'
complete -c dropdb -s h --description 'Specifies the host name of the machine on which the server is running.'
complete -c dropdb -s p --description 'Specifies the TCP port or local Unix domain socket file extension on which th…'
complete -c dropdb -s U --description 'User name to connect as.'
complete -c dropdb -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c dropdb -o 'W
.br
--password' --description 'Force dropdb to prompt for a password before connecting to a database.'
complete -c dropdb -l maintenance-db --description 'Specifies the name of the database to connect to in order to drop the target …'
complete -c dropdb -s e --description '.'
complete -c dropdb -l echo --description '.'
complete -c dropdb -s i --description '.'
complete -c dropdb -l interactive --description '.'
complete -c dropdb -s V --description '.'
complete -c dropdb -l version --description '.'
complete -c dropdb -s '?' --description '.'
complete -c dropdb -l help --description '.'
complete -c dropdb -l host --description '.'
complete -c dropdb -l port --description '.'
complete -c dropdb -l username --description '.'
complete -c dropdb -s w --description '.'
complete -c dropdb -l no-password --description '.'
complete -c dropdb -s W --description '.'
complete -c dropdb -l password --description '.'

