# git-log
# Autogenerated from man page /usr/share/man/man1/git-log.1.gz
complete -c git-log -l exclude-promisor-objects --description '(For internal use only. ) Prefilter object traversal at promisor boundary.'
complete -c git-log -s r --description 'Show recursive diffs.'
complete -c git-log -l missing --description 'because it limits the traversal, rather than just silencing errors about miss…'

