# git-pull
# Autogenerated from man page /usr/share/man/man1/git-pull.1.gz
complete -c git-pull -s u -l update-head-ok --description 'By default git fetch refuses to update the head which corresponds to the curr…'

