# git-stash
# Autogenerated from man page /usr/share/man/man1/git-stash.1.gz
complete -c git-stash -s m -l message --description 'Save your local modifications to a new stash entry and roll them back to HEAD…'

