# initdb
# Autogenerated from man page /usr/share/man/man1/initdb.1.gz
complete -c initdb -s A --description 'This option specifies the default authentication method for local users used …'
complete -c initdb -l auth-host --description 'This option specifies the authentication method for local users via TCP/IP co…'
complete -c initdb -l auth-local --description 'This option specifies the authentication method for local users via Unix-doma…'
complete -c initdb -s D --description 'This option specifies the directory where the database cluster should be stor…'
complete -c initdb -s E --description 'Selects the encoding of the template database.'
complete -c initdb -o 'k
.br
--data-checksums' --description 'Use checksums on data pages to help detect corruption by the I/O system that …'
complete -c initdb -l locale --description 'Sets the default locale for the database cluster.'
complete -c initdb -l lc-collate --description 'Like --locale, but only sets the locale in the specified category.'
complete -c initdb -l no-locale --description 'Equivalent to --locale=C.'
complete -c initdb -o 'N
.br
--no-sync' --description 'By default, initdb will wait for all files to be written safely to disk.'
complete -c initdb -l pwfile --description 'Makes initdb read the database superuser\\*(Aqs password from a file.'
complete -c initdb -o 'S
.br
--sync-only' --description 'Safely write all database files to disk and exit.'
complete -c initdb -s T --description 'Sets the default text search configuration.'
complete -c initdb -s U --description 'Selects the user name of the database superuser.'
complete -c initdb -o 'W
.br
--pwprompt' --description 'Makes initdb prompt for a password to give the database superuser.'
complete -c initdb -s X --description 'This option specifies the directory where the write-ahead log should be store…'
complete -c initdb -o 'd
.br
--debug' --description 'Print debugging output from the bootstrap backend and a few other messages of…'
complete -c initdb -s L --description 'Specifies where initdb should find its input files to initialize the database…'
complete -c initdb -o 'n
.br
--no-clean' --description 'By default, when initdb determines that an error prevented it from completely…'
complete -c initdb -o 'V
.br
--version' --description 'Print the initdb version and exit.'
complete -c initdb -o '?
.br
--help' --description 'Show help about initdb command line arguments, and exit.'
complete -c initdb -l lc-ctype --description 'options.'
complete -c initdb -l encoding --description 'Section 23. 3.  OPTIONS.'
complete -c initdb -l auth --description '.'
complete -c initdb -l pgdata --description '.'
complete -c initdb -s k --description '.'
complete -c initdb -l data-checksums --description '.'
complete -c initdb -l lc-messages --description '.'
complete -c initdb -l lc-monetary --description '.'
complete -c initdb -l lc-numeric --description '.'
complete -c initdb -l lc-time --description '.'
complete -c initdb -s N --description '.'
complete -c initdb -l no-sync --description '.'
complete -c initdb -s S --description '.'
complete -c initdb -l sync-only --description '.'
complete -c initdb -l text-search-config --description '.'
complete -c initdb -l username --description '.'
complete -c initdb -s W --description '.'
complete -c initdb -l pwprompt --description '.'
complete -c initdb -l waldir --description '.'
complete -c initdb -s d --description '.'
complete -c initdb -l debug --description '.'
complete -c initdb -s n --description '.'
complete -c initdb -l no-clean --description '.'
complete -c initdb -s V --description '.'
complete -c initdb -l version --description '.'
complete -c initdb -s '?' --description '.'
complete -c initdb -l help --description '.'

