# myisam_ftdump
# Autogenerated from man page /usr/share/man/man1/myisam_ftdump.1.gz
complete -c myisam_ftdump -l help --description '.'
complete -c myisam_ftdump -s h --description '.'
complete -c myisam_ftdump -s '?' --description 'Display a help message and exit.  oc o 2. 3.'
complete -c myisam_ftdump -l count --description '.'
complete -c myisam_ftdump -s c --description 'Calculate per-word statistics (counts and global weights).  oc o 2. 3.'
complete -c myisam_ftdump -l dump --description '.'
complete -c myisam_ftdump -s d --description 'Dump the index, including data offsets and word weights.  oc o 2. 3.'
complete -c myisam_ftdump -l length --description '.'
complete -c myisam_ftdump -s l --description 'Report the length distribution.  oc o 2. 3.'
complete -c myisam_ftdump -l stats --description '.'
complete -c myisam_ftdump -s s --description 'Report global index statistics.'
complete -c myisam_ftdump -l verbose --description '.'
complete -c myisam_ftdump -s v --description 'Verbose mode.  Print more output about what the program does.'

