# mysqldumpslow
# Autogenerated from man page /usr/share/man/man1/mysqldumpslow.1.gz
complete -c mysqldumpslow -s a --description 'and.'
complete -c mysqldumpslow -s n --description 'options.'
complete -c mysqldumpslow -l help --description 'Display a help message and exit.  oc o 2. 3.'
complete -c mysqldumpslow -l debug --description '.'
complete -c mysqldumpslow -s d --description 'Run in debug mode.'
complete -c mysqldumpslow -s g --description '.'
complete -c mysqldumpslow -s h --description '.'
complete -c mysqldumpslow -s i --description '.'
complete -c mysqldumpslow -s l --description '.'
complete -c mysqldumpslow -s r --description '.'
complete -c mysqldumpslow -s s --description '.'
complete -c mysqldumpslow -s t --description '.'
complete -c mysqldumpslow -l verbose --description '.'
complete -c mysqldumpslow -s v --description 'Verbose mode.  Print more information about what the program does.'

