# mysqld_multi
# Autogenerated from man page /usr/share/man/man1/mysqld_multi.1.gz
complete -c mysqld_multi -l defaults-file --description 'option).  N can be any positive integer.'
complete -c mysqld_multi -l no-defaults --description 'oc o 2. 3.'
complete -c mysqld_multi -l defaults-extra-file --description 'option, if one is given.'
complete -c mysqld_multi -l help --description 'Display a help message and exit.  oc o 2. 3.'
complete -c mysqld_multi -l example --description 'Display a sample option file.  oc o 2. 3.'
complete -c mysqld_multi -l log --description 'Specify the name of the log file.'
complete -c mysqld_multi -l mysqladmin --description 'The mysqladmin binary to be used to stop servers.  oc o 2. 3.'
complete -c mysqld_multi -l mysqld --description 'The mysqld binary to be used.'
complete -c mysqld_multi -l no-log --description 'Print log information to stdout rather than to the log file.'
complete -c mysqld_multi -l password --description 'The password of the MySQL account to use when invoking mysqladmin.'
complete -c mysqld_multi -l silent --description 'Silent mode; disable warnings.  oc o 2. 3.'
complete -c mysqld_multi -l tcp-ip --description 'Connect to each MySQL server through the TCP/IP port instead of the Unix sock…'
complete -c mysqld_multi -l user --description 'The user name of the MySQL account to use when invoking mysqladmin.  oc o 2.'
complete -c mysqld_multi -l verbose --description 'Be more verbose.  oc o 2. 3.'
complete -c mysqld_multi -l version --description 'Display version information and exit.  Some notes about mysqld_multi: oc o 2.'
complete -c mysqld_multi -l pid-file --description 'option is very important if you are using mysqld_safe to start mysqld (for ex…'

