# nginx
# Autogenerated from man page /usr/share/man/man8/nginx.8.gz
complete -c nginx -s '?' --description 'Print help.'
complete -c nginx -s c --description 'Use an alternative configuration file.'
complete -c nginx -s g --description 'Set global configuration directives.  See EXAMPLES for details.'
complete -c nginx -s p --description 'Set the prefix path.  The default value is /usr/share/nginx.'
complete -c nginx -s q --description 'Suppress non-error messages during configuration testing.'
complete -c nginx -s s --description 'Send a signal to the master process.'
complete -c nginx -s t --description 'Do not run, just test the configuration file.'
complete -c nginx -s T --description 'Same as t, but additionally dump configuration files to standard output.'
complete -c nginx -s V --description 'Print the nginx version, compiler version, and configure script parameters.'
complete -c nginx -s v --description 'Print the nginx version.'

