# node
# Autogenerated from man page /usr/share/man/man1/node.1.gz
complete -c node -l version --description 'Print node\'s version.'
complete -c node -l help --description 'Print node command line options.'
complete -c node -l eval --description 'Evaluate the following argument as JavaScript.'
complete -c node -l print --description 'Identical to -e but prints the result.'
complete -c node -l check --description 'Syntax check the script without executing.'
complete -c node -l interactive --description 'Open the REPL even if stdin does not appear to be a terminal.'
complete -c node -l require --description 'Preload the specified module at startup.'
complete -c node -l force-async-hooks-checks --description 'Enables runtime checks for `async_hooks`.'
complete -c node -l use-openssl-ca --description 'Use OpenSSL\'s default CA store or use bundled Mozilla CA store as supplied by…'
complete -c node -l stack_trace_limit --description '.'

