# perror
# Autogenerated from man page /usr/share/man/man1/perror.1.gz
complete -c perror -l help --description '.'
complete -c perror -l info --description '.'
complete -c perror -s I --description '.'
complete -c perror -s '?' --description 'Display a help message and exit.  oc o 2. 3.'
complete -c perror -l ndb --description 'Print the error message for an NDB Cluster error code.'
complete -c perror -l silent --description '.'
complete -c perror -s s --description 'Silent mode.  Print only the error message.  oc o 2. 3.'
complete -c perror -l verbose --description '.'
complete -c perror -s v --description 'Verbose mode.  Print error code and message.  This is the default behavior.'
complete -c perror -l version --description '.'
complete -c perror -s V --description 'Display version information and exit.'

