# pg_archivecleanup
# Autogenerated from man page /usr/share/man/man1/pg_archivecleanup.1.gz
complete -c pg_archivecleanup -s d --description 'Print lots of debug logging output on stderr.'
complete -c pg_archivecleanup -s n --description 'Print the names of the files that would have been removed on stdout (performs…'
complete -c pg_archivecleanup -o 'V
.br
--version' --description 'Print the pg_archivecleanup version and exit.'
complete -c pg_archivecleanup -s x --description 'Provide an extension that will be stripped from all file names before decidin…'
complete -c pg_archivecleanup -o '?
.br
--help' --description 'Show help about pg_archivecleanup command line arguments, and exit.'
complete -c pg_archivecleanup -s V --description '.'
complete -c pg_archivecleanup -l version --description '.'
complete -c pg_archivecleanup -s '?' --description '.'
complete -c pg_archivecleanup -l help --description '.'

