# pg_conftool
# Autogenerated from man page /usr/share/man/man1/pg_conftool.1.gz
complete -c pg_conftool -s b -l boolean --description 'Format boolean value as on or off (not for \\*(L"show all\\*(R").'
complete -c pg_conftool -s s -l short --description 'Show only the value (instead of key = value pair).'
complete -c pg_conftool -s v -l verbose --description 'Verbose output.'

