# pg_ctlcluster
# Autogenerated from man page /usr/share/man/man1/pg_ctlcluster.1.gz
complete -c pg_ctlcluster -s f -l force --description 'For stop and restart, the \\*(L"fast\\*(R" mode is used which rolls back all ac…'
complete -c pg_ctlcluster -s m -l mode --description 'Shutdown mode to use for stop and restart actions, default is smart.'
complete -c pg_ctlcluster -l foreground --description 'Start postgres in foreground, without daemonizing via pg_ctl.'
complete -c pg_ctlcluster -l stdlog --description 'When --foreground is in use, redirect stderr to the standard logfile in \\f(CW…'
complete -c pg_ctlcluster -l bindir --description 'Path to pg_ctl.'
complete -c pg_ctlcluster -s o -l options --description 'Pass given option as command line option to the \\f(CW\\*(C`postgres\\*(C\' proce…'

