# pg_resetwal
# Autogenerated from man page /usr/share/man/man1/pg_resetwal.1.gz
complete -c pg_resetwal -s f --description 'Force pg_resetwal to proceed even if it cannot determine valid data for pg_co…'
complete -c pg_resetwal -s n --description 'The -n (no operation) option instructs pg_resetwal to print the values recons…'
complete -c pg_resetwal -o 'V
.br
--version' --description 'Display version information, then exit.'
complete -c pg_resetwal -o '?
.br
--help' --description 'Show help, then exit.'
complete -c pg_resetwal -s c --description 'Manually set the oldest and newest transaction IDs for which the commit time …'
complete -c pg_resetwal -s e --description 'Manually set the next transaction ID\\*(Aqs epoch.'
complete -c pg_resetwal -s l --description 'Manually set the WAL starting address.'
complete -c pg_resetwal -s m --description 'Manually set the next and oldest multitransaction ID.'
complete -c pg_resetwal -s o --description 'Manually set the next OID.'
complete -c pg_resetwal -s O --description 'Manually set the next multitransaction offset.'
complete -c pg_resetwal -s x --description 'Manually set the next transaction ID.'
complete -c pg_resetwal -s V --description '.'
complete -c pg_resetwal -l version --description '.'
complete -c pg_resetwal -s '?' --description '.'
complete -c pg_resetwal -l help --description '.'

