# pg_standby
# Autogenerated from man page /usr/share/man/man1/pg_standby.1.gz
complete -c pg_standby -s c --description 'Use cp or copy command to restore WAL files from archive.'
complete -c pg_standby -s d --description 'Print lots of debug logging output on stderr.'
complete -c pg_standby -s k --description 'Remove files from archivelocation so that no more than this many WAL files be…'
complete -c pg_standby -s r --description 'Set the maximum number of times to retry the copy command if it fails (defaul…'
complete -c pg_standby -s s --description 'Set the number of seconds (up to 60, default 5) to sleep between tests to see…'
complete -c pg_standby -s t --description 'Specify a trigger file whose presence should cause failover.'
complete -c pg_standby -o 'V
.br
--version' --description 'Print the pg_standby version and exit.'
complete -c pg_standby -s w --description 'Set the maximum number of seconds to wait for the next WAL file, after which …'
complete -c pg_standby -o '?
.br
--help' --description 'Show help about pg_standby command line arguments, and exit.'
complete -c pg_standby -s V --description '.'
complete -c pg_standby -l version --description '.'
complete -c pg_standby -s '?' --description '.'
complete -c pg_standby -l help --description '.'

