# pg_test_timing
# Autogenerated from man page /usr/share/man/man1/pg_test_timing.1.gz
complete -c pg_test_timing -s d --description 'Specifies the test duration, in seconds.'
complete -c pg_test_timing -o 'V
.br
--version' --description 'Print the pg_test_timing version and exit.'
complete -c pg_test_timing -o '?
.br
--help' --description 'Show help about pg_test_timing command line arguments, and exit.'
complete -c pg_test_timing -l duration --description '.'
complete -c pg_test_timing -s V --description '.'
complete -c pg_test_timing -l version --description '.'
complete -c pg_test_timing -s '?' --description '.'
complete -c pg_test_timing -l help --description '.'

