# pg_upgrade
# Autogenerated from man page /usr/share/man/man1/pg_upgrade.1.gz
complete -c pg_upgrade -s b --description 'the old PostgreSQL executable directory; environment variable PGBINOLD.'
complete -c pg_upgrade -s B --description 'the new PostgreSQL executable directory; environment variable PGBINNEW.'
complete -c pg_upgrade -o 'c
.br
--check' --description 'check clusters only, don\\*(Aqt change any data.'
complete -c pg_upgrade -s d --description 'the old database cluster configuration directory; environment variable PGDATA…'
complete -c pg_upgrade -s D --description 'the new database cluster configuration directory; environment variable PGDATA…'
complete -c pg_upgrade -s j --description 'number of simultaneous processes or threads to use.'
complete -c pg_upgrade -o 'k
.br
--link' --description 'use hard links instead of copying files to the new cluster.'
complete -c pg_upgrade -s o --description 'options to be passed directly to the old postgres command; multiple option in…'
complete -c pg_upgrade -s O --description 'options to be passed directly to the new postgres command; multiple option in…'
complete -c pg_upgrade -s p --description 'the old cluster port number; environment variable PGPORTOLD.'
complete -c pg_upgrade -s P --description 'the new cluster port number; environment variable PGPORTNEW.'
complete -c pg_upgrade -o 'r
.br
--retain' --description 'retain SQL and log files even after successful completion.'
complete -c pg_upgrade -s U --description 'cluster\\*(Aqs install user name; environment variable PGUSER.'
complete -c pg_upgrade -o 'v
.br
--verbose' --description 'enable verbose internal logging.'
complete -c pg_upgrade -o 'V
.br
--version' --description 'display version information, then exit.'
complete -c pg_upgrade -o '?
.br
--help' --description 'show help, then exit.'
complete -c pg_upgrade -l old-bindir --description '.'
complete -c pg_upgrade -l new-bindir --description '.'
complete -c pg_upgrade -s c --description '.'
complete -c pg_upgrade -l check --description '.'
complete -c pg_upgrade -l old-datadir --description '.'
complete -c pg_upgrade -l new-datadir --description '.'
complete -c pg_upgrade -l jobs --description '.'
complete -c pg_upgrade -s k --description '.'
complete -c pg_upgrade -l link --description '.'
complete -c pg_upgrade -l old-options --description '.'
complete -c pg_upgrade -l new-options --description '.'
complete -c pg_upgrade -l old-port --description '.'
complete -c pg_upgrade -l new-port --description '.'
complete -c pg_upgrade -s r --description '.'
complete -c pg_upgrade -l retain --description '.'
complete -c pg_upgrade -l username --description '.'
complete -c pg_upgrade -s v --description '.'
complete -c pg_upgrade -l verbose --description '.'
complete -c pg_upgrade -s V --description '.'
complete -c pg_upgrade -l version --description '.'
complete -c pg_upgrade -s '?' --description '.'
complete -c pg_upgrade -l help --description '.'
complete -c pg_upgrade -l dry-run --description 'option.'

