# pg_waldump
# Autogenerated from man page /usr/share/man/man1/pg_waldump.1.gz
complete -c pg_waldump -o 'b
.br
--bkp-details' --description 'Output detailed information about backup blocks.'
complete -c pg_waldump -s e --description 'Stop reading at the specified WAL location, instead of reading to the end of …'
complete -c pg_waldump -o 'f
.br
--follow' --description 'After reaching the end of valid WAL, keep polling once per second for new WAL…'
complete -c pg_waldump -s n --description 'Display the specified number of records, then stop.'
complete -c pg_waldump -s p --description 'Specifies a directory to search for log segment files or a directory with a p…'
complete -c pg_waldump -s r --description 'Only display records generated by the specified resource manager.'
complete -c pg_waldump -s s --description 'WAL location at which to start reading.'
complete -c pg_waldump -s t --description 'Timeline from which to read log records.'
complete -c pg_waldump -o 'V
.br
--version' --description 'Print the pg_waldump version and exit.'
complete -c pg_waldump -s x --description 'Only display records marked with the given transaction ID.'
complete -c pg_waldump -o 'z
.br
--stats' --description 'Display summary statistics (number and size of records and full-page images) …'
complete -c pg_waldump -o '?
.br
--help' --description 'Show help about pg_waldump command line arguments, and exit.'
complete -c pg_waldump -s b --description '.'
complete -c pg_waldump -l bkp-details --description '.'
complete -c pg_waldump -l end --description '.'
complete -c pg_waldump -s f --description '.'
complete -c pg_waldump -l follow --description '.'
complete -c pg_waldump -l limit --description '.'
complete -c pg_waldump -l path --description '.'
complete -c pg_waldump -l rmgr --description '.'
complete -c pg_waldump -l start --description '.'
complete -c pg_waldump -l timeline --description '.'
complete -c pg_waldump -s V --description '.'
complete -c pg_waldump -l version --description '.'
complete -c pg_waldump -l xid --description '.'
complete -c pg_waldump -s z --description '.'
complete -c pg_waldump -l stats --description '.'
complete -c pg_waldump -s '?' --description '.'
complete -c pg_waldump -l help --description '.'

