# psql
# Autogenerated from man page /usr/share/man/man1/psql.1.gz
complete -c psql -o 'a
.br
--echo-all' --description 'Print all nonempty input lines to standard output as they are read.'
complete -c psql -o 'A
.br
--no-align' --description 'Switches to unaligned output mode.'
complete -c psql -o 'b
.br
--echo-errors' --description 'Print failed SQL commands to standard error output.'
complete -c psql -s c --description 'Specifies that psql is to execute the given command string, command.'
complete -c psql -s d --description 'Specifies the name of the database to connect to.'
complete -c psql -o 'e
.br
--echo-queries' --description 'Copy all SQL commands sent to the server to standard output as well.'
complete -c psql -o 'E
.br
--echo-hidden' --description 'Echo the actual queries generated by d and other backslash commands.'
complete -c psql -s f --description 'Read commands from the file filename, rather than standard input.'
complete -c psql -s F --description 'Use separator as the field separator for unaligned output.'
complete -c psql -s h --description 'Specifies the host name of the machine on which the server is running.'
complete -c psql -o 'H
.br
--html' --description 'Turn on HTML tabular output.'
complete -c psql -o 'l
.br
--list' --description 'List all available databases, then exit.'
complete -c psql -s L --description 'Write all query output into file filename, in addition to the normal output d…'
complete -c psql -o 'n
.br
--no-readline' --description 'Do not use Readline for line editing and do not use the command history.'
complete -c psql -s o --description 'Put all query output into file filename.  This is equivalent to the command o.'
complete -c psql -s p --description 'Specifies the TCP port or the local Unix-domain socket file extension on whic…'
complete -c psql -s P --description 'Specifies printing options, in the style of pset.'
complete -c psql -o 'q
.br
--quiet' --description 'Specifies that psql should do its work quietly.'
complete -c psql -s R --description 'Use separator as the record separator for unaligned output.'
complete -c psql -o 's
.br
--single-step' --description 'Run in single-step mode.'
complete -c psql -o 'S
.br
--single-line' --description 'Runs in single-line mode where a newline terminates an SQL command, as a semi…'
complete -c psql -o 't
.br
--tuples-only' --description 'Turn off printing of column names and result row count footers, etc.'
complete -c psql -s T --description 'Specifies options to be placed within the HTML table tag.'
complete -c psql -s U --description 'Connect to the database as the user username instead of the default.'
complete -c psql -s v --description 'Perform a variable assignment, like the set meta-command.'
complete -c psql -o 'V
.br
--version' --description 'Print the psql version and exit.'
complete -c psql -o 'w
.br
--no-password' --description 'Never issue a password prompt.'
complete -c psql -o 'W
.br
--password' --description 'Force psql to prompt for a password before connecting to a database, even if …'
complete -c psql -o 'x
.br
--expanded' --description 'Turn on the expanded table formatting mode.'
complete -c psql -s X --description 'Do not read the start-up file (neither the system-wide psqlrc file nor the us…'
complete -c psql -o 'z
.br
--field-separator-zero' --description 'Set the field separator for unaligned output to a zero byte.'
complete -c psql -o '0
.br
--record-separator-zero' --description 'Set the record separator for unaligned output to a zero byte.'
complete -c psql -o '1
.br
--single-transaction' --description 'This option can only be used in combination with one or more -c and/or -f opt…'
complete -c psql -o '?
.br
--help' --description 'Show help about psql and exit.'
complete -c psql -s a --description '.'
complete -c psql -l echo-all --description '.'
complete -c psql -s A --description '.'
complete -c psql -l no-align --description '.'
complete -c psql -s b --description '.'
complete -c psql -l echo-errors --description '.'
complete -c psql -l command --description '.'
complete -c psql -l dbname --description '.'
complete -c psql -s e --description '.'
complete -c psql -l echo-queries --description '.'
complete -c psql -s E --description '.'
complete -c psql -l echo-hidden --description '.'
complete -c psql -l file --description '.'
complete -c psql -s n --description 'had been specified).'
complete -c psql -l field-separator --description '.'
complete -c psql -l host --description '.'
complete -c psql -s H --description '.'
complete -c psql -l html --description '.'
complete -c psql -s l --description '.'
complete -c psql -l list --description '.'
complete -c psql -l log-file --description '.'
complete -c psql -l no-readline --description '.'
complete -c psql -l output --description '.'
complete -c psql -l port --description '.'
complete -c psql -l pset --description '.'
complete -c psql -s q --description '.'
complete -c psql -l quiet --description '.'
complete -c psql -l record-separator --description '.'
complete -c psql -s s --description '.'
complete -c psql -l single-step --description '.'
complete -c psql -s S --description '.'
complete -c psql -l single-line --description '.'
complete -c psql -s t --description '.'
complete -c psql -l tuples-only --description '.'
complete -c psql -l table-attr --description '.'
complete -c psql -l username --description '.'
complete -c psql -l set --description '.'
complete -c psql -l variable --description '.'
complete -c psql -s V --description '.'
complete -c psql -l version --description '.'
complete -c psql -s w --description '.'
complete -c psql -l no-password --description '.'
complete -c psql -s W --description '.'
complete -c psql -l password --description '.'
complete -c psql -s x --description '.'
complete -c psql -l expanded --description '.'
complete -c psql -l no-psqlrc --description '.'
complete -c psql -s z --description '.'
complete -c psql -l field-separator-zero --description '.'
complete -c psql -s 0 --description '.'
complete -c psql -l record-separator-zero --description '.'
complete -c psql -s 1 --description '.'
complete -c psql -l single-transaction --description '.'
complete -c psql -s '?' --description '.'
complete -c psql -l help --description '.'
complete -c psql -o reuse-previous --description 'or.'
complete -c psql -s '>' --description '.'
complete -c psql -l ------+---------+-----------+----------+--------- --description ' first  | integer |           | not null | 0  second | text    |           | …'
complete -c psql -l -----+-------- --description '     1 | one      2 | two      3 | three      4 | four (4 rows) You can displ…'
complete -c psql -l --- -l ---- --description '    1 one     2 two     3 three     4 four (4 rows).'
complete -c psql -l -----+--------+----- --description '     1 | one    | f      2 | two    | f      3 | three  | t      4 | four   |…'
complete -c psql -l -----+-----+-----+-------+------ --description '     1 | f   |     |       |       2 |     | f   |       |       3 |     |   …'
complete -c psql -l -+-----+-----+-----+----- --description ' 4 | 404 | 408 | 412 | 416  3 | 303 | 306 | 309 | 312  2 | 202 | 204 | 206 | …'

