# qemu-tilegx
# Autogenerated from man page /usr/share/man/man1/qemu-tilegx.1.gz
complete -c qemu-tilegx -s h --description 'Print this help.'
complete -c qemu-tilegx -s g --description 'Wait gdb connection to port 1234.'
complete -c qemu-tilegx -s L --description 'Set the elf interpreter prefix (default=/etc/qemu-binfmt/%M).'
complete -c qemu-tilegx -s s --description 'Set the stack size in bytes (default=524288).'
complete -c qemu-tilegx -s d --description 'Activate log (logfile=/tmp/qemu. log).'
complete -c qemu-tilegx -s p --description 'Set the host page size to \'pagesize\'.'

