# qemu-hppa
# Autogenerated from man page /usr/share/man/man1/qemu-hppa.1.gz
complete -c qemu-hppa -s h --description 'Print this help.'
complete -c qemu-hppa -s g --description 'Wait gdb connection to port 1234.'
complete -c qemu-hppa -s L --description 'Set the elf interpreter prefix (default=/etc/qemu-binfmt/%M).'
complete -c qemu-hppa -s s --description 'Set the stack size in bytes (default=524288).'
complete -c qemu-hppa -s d --description 'Activate log (logfile=/tmp/qemu. log).'
complete -c qemu-hppa -s p --description 'Set the host page size to \'pagesize\'.'

