# resolveip
# Autogenerated from man page /usr/share/man/man1/resolveip.1.gz
complete -c resolveip -l help --description '.'
complete -c resolveip -l info --description '.'
complete -c resolveip -s '?' --description '.'
complete -c resolveip -s I --description 'Display a help message and exit.  oc o 2. 3.'
complete -c resolveip -l silent --description '.'
complete -c resolveip -s s --description 'Silent mode.  Produce less output.  oc o 2. 3.'
complete -c resolveip -l version --description '.'
complete -c resolveip -s V --description 'Display version information and exit.'

