# sshguard
# Autogenerated from man page /usr/share/man/man8/sshguard.8.gz
complete -c sshguard -s a --description 'Block an attacker when its dangerousness exceeds thresh.'
complete -c sshguard -s b --description 'Blacklist an attacker when its dangerousness exceeds thresh.'
complete -c sshguard -s f --description 'Deprecated.  See LOG VALIDATION below.'
complete -c sshguard -s i --description 'Write the PID of sshguard to pidfile.'
complete -c sshguard -s l --description 'Monitor source for log messages.'
complete -c sshguard -s p --description 'Wait at least interval seconds before releasing a blocked address.'
complete -c sshguard -s s --description 'Forget about an attacker interval seconds after its last attempt.'
complete -c sshguard -s w --description 'Whitelist the given address, hostname, or address block.'
complete -c sshguard -s v --description 'Print version information and exit.'

