# update-service
# Autogenerated from man page /usr/share/man/man8/update-service.8.gz
complete -c update-service -l add -s a --description 'Add the service directory  service-directory to the system-wide service super…'
complete -c update-service -l remove -s r --description 'Remove the service directory R service-directory , which has been added under…'
complete -c update-service -l list -s l --description 'If  service-name is specified,  update-service checks whether  service-name i…'
complete -c update-service -l check -s c --description 'The same as --list, but update-service doesn\'t print anything to standard out…'

