# vam
# Autogenerated from man page /usr/share/man/man1/vam.1.gz
complete -c vam -s h -l help --description 'show this usage message and exit.'
complete -c vam -s q -l query --description 'be quiet and make the output more parseable (for "status").'
complete -c vam -s r -l registry-dir --description 'set the registry directory (default: /usr/share/vim/registry).'
complete -c vam -s s -l source-dir --description 'set the addons source directory (default: /usr/share/vim/addons).'
complete -c vam -s t -l target-dir --description 'set the addons target directory (default: $HOME/. vim).'
complete -c vam -s v -l verbose --description 'increase verbosity level.'
complete -c vam -s z -l silent --description 'silent mode: suppress most of the output.'
complete -c vam -s y -l system-dir --description 'set the system-wide target directory (default: /var/lib/vim/addons).'
complete -c vam -s w -l system-wide --description 'set the addons target directory to the system-wide target directory, possibly…'

