# wmdocker
# Autogenerated from man page /usr/share/man/man1/wmdocker.1.gz
complete -c wmdocker -o h-help --description 'Show summary of options.'
complete -c wmdocker -o display --description 'The X display to connect to.'
complete -c wmdocker -o border --description 'The width of the border to put around the system tray icons.  Defaults to 1.'
complete -c wmdocker -o vertical --description 'Line up the icons vertically.  Defaults to horizontally.'
complete -c wmdocker -o wmaker --description 'WindowMaker mode.'
complete -c wmdocker -o iconsize --description 'The size (width and height and height) to display icons as in the system tray.'
complete -c wmdocker -o color --description 'The background color to use for the tray.'

